// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://svqxmpwfyyhseztcuhkt.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InN2cXhtcHdmeXloc2V6dGN1aGt0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3Njg0MTQyOTcsImV4cCI6MjA4Mzk5MDI5N30.PifsAtouwMOusb27EW9wp7N3f06W5BXhRTqgrrtZjTI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});